import React from 'react';
import ThemeProviderCustom from '../contexts/CreateTheme';
import '../globals.css';
import type { Metadata } from 'next';

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function AuthenticatedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <ThemeProviderCustom>{children}</ThemeProviderCustom>
      </body>
    </html>
  );
}
