import React from "react";
import ThemeProviderCuston from "../contexts/CreateTheme";
import "../globals.css";
import type { Metadata } from "next";

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <ThemeProviderCuston>{children}</ThemeProviderCuston>
      </body>
    </html>
  );
}
